# Generated by Django 5.1.1 on 2024-11-18 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDes', models.TextField()),
                ('Assign_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('category', models.ManyToManyField(to='category.categorymodel')),
            ],
        ),
    ]
